name: Linux Commands Workflow

on:
  push:
    branches:
      - main

jobs:
  linux-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Current User
        run: whoami

      - name: Current Directory
        run: pwd

      - name: Current Date
        run: date

      - name: List Files
        run: ls -la
